---
- name: Configure TACACs
  hosts: ios
  gather_facts: no
  vars:
    - output_directory: ./output
  tasks:  
    #--------------------------------------------------------
    # Gather ansible facts to set timestamps
    #--------------------------------------------------------

    - name: Gather ansible facts from localhost
      setup:
      delegate_to: localhost
      run_once: yes

    - name: Set Facts
      set_fact:
        yyyymmdd: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"
        yyyymmddhh: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}"
        yyyymmddhhmm: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
      delegate_to: localhost
      run_once: yes

    - name: Create Output Directory
      file:
        path: "{{ output_directory }}/{{ yyyymmddhhmm }}"
        state: directory
      delegate_to: localhost
      run_once: yes

    #--------------------------------------------------------
    # Get existing TACACs config, print to screen and write to file
    #--------------------------------------------------------

    - name: "Gather ansible ios_facts"
      ios_facts:
      register: ios_facts

    - name: Debug IOS Facts
      debug:
        msg: "{{ ios_facts }}"

    - name:  "Gather existing TACACs configuration"
      ios_command:
        commands: 
          - "show run | section [Tt][Aa][Cc][Aa][Cc][Ss]"
      register: tacacs_config_before

    - name: "TACACs Config Before"
      debug:
        msg: "{{ tacacs_config_before.stdout_lines }}"
      tags:
        - debug

    - name: Write previous TACACs configuration to file
      copy:
        content: "{{ tacacs_config_before.stdout.0 }}"
        dest: "{{ output_directory }}/{{ yyyymmddhhmm }}/{{ inventory_hostname }}-tacacs_config_before.txt"
      delegate_to: localhost

    - name: Write Output Header to file
      lineinfile:
        line: "\n\n\n!-- {{ inventory_hostname }} - tacacs_config_before - {{ yyyymmddhhmm }} --!\n"
        path: "{{ output_directory }}/{{ yyyymmddhhmm }}/{{ inventory_hostname }}-tacacs_config_before.txt"
        create: yes
        #backrefs: yes
        insertbefore: BOF
      delegate_to: localhost


    - name: Add Previous TACACs config to a central file
      shell: "/bin/cat {{ output_directory }}/{{ yyyymmddhhmm }}/{{ inventory_hostname }}-tacacs_config_before.txt >> {{ output_directory }}/{{ yyyymmddhhmm }}/all-ios-tacacs_config_before.txt"
      delegate_to: localhost
      tags:
        - consolidate
